"""baseline pre-billing schema (plan 039/001)

Snapshot of the 15 core tables as cloud/main.py's startup DDL created them
before Alembic existed. Autogenerated from cloud/db/models.py, hand-verified,
and frozen. Existing production databases are stamped at this revision (see
cloud/db/migrate.py); fresh databases run it for real.

Revision ID: 0001
Revises:
Create Date: 2026-07-13
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Hand-verified against the models; frozen — do not regenerate.
    op.create_table('app_settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('gateway_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('kinds', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tier', sa.Text(), nullable=True),
    sa.Column('input_cost', sa.Float(), nullable=True),
    sa.Column('output_cost', sa.Float(), nullable=True),
    sa.Column('recommended_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deprecated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'model')
    )
    op.create_table('gateway_services',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('upstream_url', sa.Text(), nullable=False),
    sa.Column('auth_style', sa.Text(), nullable=False),
    sa.Column('luna_credential_name', sa.Text(), nullable=False),
    sa.Column('luna_env_key_var', sa.Text(), nullable=False),
    sa.Column('luna_env_base_url_var', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('provision_by_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('extra_env', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('google_sub', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_sub')
    )
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('plan', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('gateway_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_slug', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('api_key_enc', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_slug'], ['gateway_services.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_slug', 'scope', 'priority')
    )
    op.create_index('ix_gateway_keys_service_scope', 'gateway_keys', ['service_slug', 'scope'], unique=False)
    op.create_table('luna_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('registry_tag', sa.Text(), nullable=False),
    sa.Column('is_main', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('build_status', sa.Text(), nullable=False),
    sa.Column('build_run_id', sa.Text(), nullable=True),
    sa.Column('build_error', sa.Text(), nullable=True),
    sa.Column('git_sha', sa.Text(), nullable=True),
    sa.Column('git_branch', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('image_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cache_warmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sdk_major', sa.Integer(), nullable=True),
    sa.Column('sdk_min_major', sa.Integer(), nullable=True),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('plugin_catalog',
    sa.Column('plugin_name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('marketplace_url', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('tier', sa.Text(), nullable=False),
    sa.Column('service_slug', sa.Text(), nullable=True),
    sa.Column('key_mode', sa.Text(), nullable=False),
    sa.Column('suggested', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_slug'], ['gateway_services.slug'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('plugin_name')
    )
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('runtime_kind', sa.Text(), nullable=True),
    sa.Column('runtime_ref', sa.Text(), nullable=True),
    sa.Column('internal_url', sa.Text(), nullable=True),
    sa.Column('db_schema', sa.Text(), nullable=True),
    sa.Column('vault_key_ref', sa.Text(), nullable=True),
    sa.Column('volume_id', sa.Text(), nullable=True),
    sa.Column('volume_region', sa.Text(), nullable=True),
    sa.Column('volume_size_gb', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('image_version', sa.Text(), nullable=True),
    sa.Column('cached_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cached_metrics_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actor_ip', sa.Text(), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_account_id', 'audit_log', ['account_id'], unique=False)
    op.create_index('ix_audit_log_action', 'audit_log', ['action'], unique=False)
    op.create_index('ix_audit_log_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'user_id')
    )
    op.create_table('composio_account_links',
    sa.Column('connected_account_id', sa.Text(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('app_name', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('connected_account_id')
    )
    op.create_table('gateway_tenant_tokens',
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_table('relay_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('webhook_id', sa.Text(), nullable=False),
    sa.Column('connected_account_id', sa.Text(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status_code', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('webhook_id')
    )
    op.create_index('ix_relay_deliveries_created', 'relay_deliveries', ['created_at'], unique=False)
    op.create_index('ix_relay_deliveries_status_next', 'relay_deliveries', ['status', 'next_attempt_at'], unique=False)
    op.create_table('usage_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('service_slug', sa.Text(), nullable=False),
    sa.Column('billable', sa.Boolean(), nullable=False),
    sa.Column('key_id', sa.UUID(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_events_agent_created', 'usage_events', ['agent_id', 'created_at'], unique=False)
    op.create_index('ix_usage_events_service_created', 'usage_events', ['service_slug', 'created_at'], unique=False)


def downgrade() -> None:
    # Hand-verified against the models; frozen — do not regenerate.
    op.drop_index('ix_usage_events_service_created', table_name='usage_events')
    op.drop_index('ix_usage_events_agent_created', table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index('ix_relay_deliveries_status_next', table_name='relay_deliveries')
    op.drop_index('ix_relay_deliveries_created', table_name='relay_deliveries')
    op.drop_table('relay_deliveries')
    op.drop_table('gateway_tenant_tokens')
    op.drop_table('composio_account_links')
    op.drop_table('memberships')
    op.drop_index('ix_audit_log_created_at', table_name='audit_log')
    op.drop_index('ix_audit_log_action', table_name='audit_log')
    op.drop_index('ix_audit_log_account_id', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('agents')
    op.drop_table('plugin_catalog')
    op.drop_table('luna_images')
    op.drop_index('ix_gateway_keys_service_scope', table_name='gateway_keys')
    op.drop_table('gateway_keys')
    op.drop_table('accounts')
    op.drop_table('users')
    op.drop_table('gateway_services')
    op.drop_table('gateway_models')
    op.drop_table('app_settings')
