"""billing schema (plan 039/001)

Autogenerated from cloud/billing/models.py, then hand-verified and frozen —
this file never changes when the models change; later phases add new
revisions. The trigger block at the end is hand-written and Postgres-only:
- postings must sum to zero per transaction at COMMIT (deferred trigger);
- posted transactions and postings are immutable (no UPDATE/DELETE);
- published/retired pricing versions are immutable except published→retired;
- grant lots and consumptions can never be deleted.

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-13
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Hand-verified against the models; frozen — do not regenerate.
    op.create_table('billing_outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedupe_key', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('leased_by', sa.Text(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending','running','succeeded','failed','dead')", name='ck_bo_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_index('ix_bo_claim', 'billing_outbox', ['status', 'next_attempt_at'], unique=False)
    op.create_table('processed_webhooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=True),
    sa.Column('object_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'event_id')
    )
    op.create_table('commercial_pricing_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config_schema_version', sa.Integer(), nullable=False),
    sa.Column('config_hash', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft','published','retired')", name='ck_cpv_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_version_id'], ['commercial_pricing_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_number')
    )
    op.create_table('provider_cost_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config_hash', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft','published','retired')", name='ck_pcv_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_number')
    )
    op.create_table('commercial_pricing_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('commercial_pricing_version_id', sa.UUID(), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('audit_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source IN ('new_account_default','global_rollout','manual_test','migration')", name='ck_cpa_source'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['commercial_pricing_version_id'], ['commercial_pricing_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cpa_account_effective', 'commercial_pricing_assignments', ['account_id', 'effective_at'], unique=False)
    op.create_table('commercial_pricing_rollouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commercial_pricing_version_id', sa.UUID(), nullable=False),
    sa.Column('audience', sa.Text(), nullable=False),
    sa.Column('selected_account_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('migration_policy', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('accounts_scheduled', sa.Integer(), nullable=False),
    sa.Column('accounts_applied', sa.Integer(), nullable=False),
    sa.Column('accounts_failed', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("audience IN ('new_accounts','all_accounts','selected_accounts')", name='ck_cpr_audience'),
    sa.ForeignKeyConstraint(['commercial_pricing_version_id'], ['commercial_pricing_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing_simulations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('baseline_version_id', sa.UUID(), nullable=True),
    sa.Column('candidate_version_id', sa.UUID(), nullable=True),
    sa.Column('provider_cost_basis', sa.Text(), nullable=True),
    sa.Column('transforms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('config_hash', sa.Text(), nullable=True),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['baseline_version_id'], ['commercial_pricing_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['candidate_version_id'], ['commercial_pricing_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_cost_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_cost_version_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('sku', sa.Text(), nullable=False),
    sa.Column('region_tier', sa.Text(), nullable=True),
    sa.Column('dimension', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('rate_numerator', sa.BigInteger(), nullable=False),
    sa.Column('rate_denominator', sa.BigInteger(), nullable=False),
    sa.Column('quality', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("quality IN ('estimated','provider_confirmed','reconciled')", name='ck_pcr_quality'),
    sa.CheckConstraint('rate_denominator > 0', name='ck_pcr_denominator'),
    sa.CheckConstraint('rate_numerator >= 0', name='ck_pcr_numerator'),
    sa.ForeignKeyConstraint(['provider_cost_version_id'], ['provider_cost_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_cost_version_id', 'provider', 'sku', 'dimension')
    )
    op.create_table('agent_credit_limits',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('daily_limit_credits', sa.BigInteger(), nullable=True),
    sa.Column('monthly_limit_credits', sa.BigInteger(), nullable=True),
    sa.Column('warning_threshold_pct', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('agent_limit_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('period_kind', sa.Text(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settled_credits', sa.BigInteger(), nullable=False),
    sa.Column('open_exposure_credits', sa.BigInteger(), nullable=False),
    sa.Column('last_seq', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("period_kind IN ('daily','monthly')", name='ck_alp_kind'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'period_kind', 'period_start')
    )
    op.create_table('billing_accounts',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('billing_status', sa.Text(), nullable=False),
    sa.Column('current_assignment_id', sa.UUID(), nullable=True),
    sa.Column('stripe_customer_id', sa.Text(), nullable=True),
    sa.Column('auto_topup', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('overrun_cap_credits', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['current_assignment_id'], ['commercial_pricing_assignments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    op.create_table('account_balance_projections',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('posted_balance_credits', sa.BigInteger(), nullable=False),
    sa.Column('bonus_credits', sa.BigInteger(), nullable=False),
    sa.Column('gift_credits', sa.BigInteger(), nullable=False),
    sa.Column('free_credits', sa.BigInteger(), nullable=False),
    sa.Column('paid_credits', sa.BigInteger(), nullable=False),
    sa.Column('topup_credits', sa.BigInteger(), nullable=False),
    sa.Column('debt_credits', sa.BigInteger(), nullable=False),
    sa.Column('open_exposure_credits', sa.BigInteger(), nullable=False),
    sa.Column('next_expiry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seq', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['billing_accounts.account_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('billable_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_idempotency_key', sa.Text(), nullable=False),
    sa.Column('call_id', sa.Text(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('root_action_id', sa.Text(), nullable=True),
    sa.Column('root_action_type', sa.Text(), nullable=True),
    sa.Column('job_id', sa.Text(), nullable=True),
    sa.Column('plugin', sa.Text(), nullable=True),
    sa.Column('service', sa.Text(), nullable=False),
    sa.Column('sku', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('model_tier', sa.Text(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('provider_request_id', sa.Text(), nullable=True),
    sa.Column('provider_response_id', sa.Text(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('quantity_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vendor_cost_micro_usd', sa.BigInteger(), nullable=False),
    sa.Column('cost_source', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("context IN ('agent','direct','forge')", name='ck_be_context'),
    sa.CheckConstraint("cost_source IN ('provider_usage','catalog','reconciled','estimated')", name='ck_be_cost_source'),
    sa.ForeignKeyConstraint(['account_id'], ['billing_accounts.account_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_idempotency_key')
    )
    op.create_index('ix_be_account_event_at', 'billable_events', ['account_id', 'event_at'], unique=False)
    op.create_index('ix_be_call', 'billable_events', ['call_id'], unique=False)
    op.create_table('credit_ledger_transactions',
    sa.Column('seq', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('request_hash', sa.Text(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('root_action_id', sa.Text(), nullable=True),
    sa.Column('service', sa.Text(), nullable=True),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('reversal_of_id', sa.UUID(), nullable=True),
    sa.Column('commercial_pricing_version_id', sa.UUID(), nullable=True),
    sa.Column('provider_cost_version_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("type IN ('grant','charge','expiration','refund','reversal','adjustment','debt_repayment')", name='ck_clt_type'),
    sa.ForeignKeyConstraint(['account_id'], ['billing_accounts.account_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['commercial_pricing_version_id'], ['commercial_pricing_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_cost_version_id'], ['provider_cost_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversal_of_id'], ['credit_ledger_transactions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('seq'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_clt_account_seq', 'credit_ledger_transactions', ['account_id', 'seq'], unique=False)
    op.create_table('resource_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('resource_kind', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('sku', sa.Text(), nullable=True),
    sa.Column('provider_resource_id', sa.Text(), nullable=True),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accrued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reconcile_state', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['billing_accounts.account_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ra_agent', 'resource_allocations', ['agent_id'], unique=False)
    op.create_table('usage_rollups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('day', sa.DateTime(timezone=True), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('service', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('calls', sa.BigInteger(), nullable=False),
    sa.Column('quantities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('credits', sa.BigInteger(), nullable=False),
    sa.Column('vendor_cost_micro_usd', sa.BigInteger(), nullable=False),
    sa.Column('estimated_count', sa.BigInteger(), nullable=False),
    sa.Column('reconciled_count', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['billing_accounts.account_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', 'account_id', 'agent_id', 'service', 'context', 'model')
    )
    op.create_table('agent_hosting_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_credits', sa.BigInteger(), nullable=False),
    sa.Column('commercial_pricing_version_id', sa.UUID(), nullable=True),
    sa.Column('charge_transaction_id', sa.UUID(), nullable=True),
    sa.Column('resource_allocation_id', sa.UUID(), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state IN ('pending','paid','active','ended','payment_due','stopped')", name='ck_ahp_state'),
    sa.ForeignKeyConstraint(['account_id'], ['billing_accounts.account_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['charge_transaction_id'], ['credit_ledger_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['commercial_pricing_version_id'], ['commercial_pricing_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resource_allocation_id'], ['resource_allocations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'starts_at')
    )
    op.create_table('billing_holds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operation_id', sa.Text(), nullable=False),
    sa.Column('request_hash', sa.Text(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('root_action_id', sa.Text(), nullable=True),
    sa.Column('service', sa.Text(), nullable=True),
    sa.Column('sku', sa.Text(), nullable=True),
    sa.Column('commercial_pricing_version_id', sa.UUID(), nullable=True),
    sa.Column('provider_cost_version_id', sa.UUID(), nullable=True),
    sa.Column('estimated_credits', sa.BigInteger(), nullable=False),
    sa.Column('overrun_credits', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('settle_transaction_id', sa.UUID(), nullable=True),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('open','settled','released','expired','needs_reconciliation')", name='ck_hold_status'),
    sa.CheckConstraint('estimated_credits >= 0', name='ck_hold_estimate_nonneg'),
    sa.CheckConstraint('overrun_credits >= 0', name='ck_hold_overrun_nonneg'),
    sa.ForeignKeyConstraint(['account_id'], ['billing_accounts.account_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['commercial_pricing_version_id'], ['commercial_pricing_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_cost_version_id'], ['provider_cost_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['settle_transaction_id'], ['credit_ledger_transactions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id')
    )
    op.create_index('ix_holds_account_status', 'billing_holds', ['account_id', 'status'], unique=False)
    op.create_table('credit_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('source_key', sa.Text(), nullable=False),
    sa.Column('original_credits', sa.BigInteger(), nullable=False),
    sa.Column('remaining_credits', sa.BigInteger(), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('visible_category', sa.Text(), nullable=False),
    sa.Column('burn_priority', sa.Integer(), nullable=False),
    sa.Column('stripe_ref', sa.Text(), nullable=True),
    sa.Column('cash_paid_micro_usd', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('grant_transaction_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source_type IN ('subscription_paid','subscription_bonus','topup','free_recurring','gift','refund','admin')", name='ck_grant_source_type'),
    sa.CheckConstraint("status IN ('scheduled','active','exhausted','expired','reversed')", name='ck_grant_status'),
    sa.CheckConstraint("visible_category IN ('bonus','gift','free','paid','topup')", name='ck_grant_category'),
    sa.CheckConstraint('expires_at IS NULL OR expires_at > effective_at', name='ck_grant_expiry_window'),
    sa.CheckConstraint('original_credits >= 0', name='ck_grant_original_nonneg'),
    sa.CheckConstraint('remaining_credits >= 0', name='ck_grant_remaining_nonneg'),
    sa.ForeignKeyConstraint(['account_id'], ['billing_accounts.account_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grant_transaction_id'], ['credit_ledger_transactions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key')
    )
    op.create_index('ix_credit_grants_account_status', 'credit_grants', ['account_id', 'status'], unique=False)
    op.create_table('credit_ledger_postings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('ledger_account', sa.Text(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('credits', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['billing_accounts.account_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['credit_ledger_transactions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clp_ledger_account', 'credit_ledger_postings', ['ledger_account'], unique=False)
    op.create_index('ix_clp_transaction', 'credit_ledger_postings', ['transaction_id'], unique=False)
    op.create_table('credit_consumptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('charge_transaction_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('grant_id', sa.UUID(), nullable=True),
    sa.Column('credits', sa.BigInteger(), nullable=False),
    sa.Column('repaid_credits', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('credits > 0', name='ck_cc_credits_positive'),
    sa.CheckConstraint('repaid_credits >= 0', name='ck_cc_repaid_nonneg'),
    sa.ForeignKeyConstraint(['account_id'], ['billing_accounts.account_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['charge_transaction_id'], ['credit_ledger_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grant_id'], ['credit_grants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cc_grant', 'credit_consumptions', ['grant_id'], unique=False)
    op.create_index('ix_cc_transaction', 'credit_consumptions', ['charge_transaction_id'], unique=False)
    op.create_table('rated_charges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('logical_call_id', sa.Text(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('hold_id', sa.UUID(), nullable=True),
    sa.Column('commercial_pricing_version_id', sa.UUID(), nullable=True),
    sa.Column('provider_cost_version_id', sa.UUID(), nullable=True),
    sa.Column('rule_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vendor_cost_micro_usd', sa.BigInteger(), nullable=False),
    sa.Column('margin_micro_usd', sa.BigInteger(), nullable=False),
    sa.Column('rounding_micro_usd', sa.BigInteger(), nullable=False),
    sa.Column('credits', sa.BigInteger(), nullable=False),
    sa.Column('luna_absorbed_micro_usd', sa.BigInteger(), nullable=False),
    sa.Column('charge_status', sa.Text(), nullable=False),
    sa.Column('ledger_transaction_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['billing_accounts.account_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['commercial_pricing_version_id'], ['commercial_pricing_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hold_id'], ['billing_holds.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ledger_transaction_id'], ['credit_ledger_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_cost_version_id'], ['provider_cost_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('logical_call_id')
    )
    op.create_index('ix_rc_account', 'rated_charges', ['account_id'], unique=False)

    if op.get_bind().dialect.name == "postgresql":
        _create_postgres_triggers()


def _create_postgres_triggers() -> None:
    # 1. Balanced postings, checked at COMMIT (a row trigger would reject the
    #    temporarily unbalanced state during multi-row inserts).
    op.execute("""
        CREATE OR REPLACE FUNCTION billing_check_balanced_postings() RETURNS trigger AS $$
        DECLARE
            total BIGINT;
            n BIGINT;
        BEGIN
            SELECT COALESCE(SUM(credits), 0), COUNT(*) INTO total, n
            FROM credit_ledger_postings WHERE transaction_id = NEW.id;
            IF n = 0 THEN
                RAISE EXCEPTION 'ledger transaction % committed with no postings', NEW.id;
            END IF;
            IF total <> 0 THEN
                RAISE EXCEPTION 'ledger transaction % postings sum to %, not zero', NEW.id, total;
            END IF;
            RETURN NEW;
        END $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE CONSTRAINT TRIGGER trg_clt_balanced
        AFTER INSERT ON credit_ledger_transactions
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW EXECUTE FUNCTION billing_check_balanced_postings();
    """)

    # 2. Immutability of posted financial rows.
    op.execute("""
        CREATE OR REPLACE FUNCTION billing_forbid_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION '% rows are immutable (%)', TG_TABLE_NAME, TG_OP;
        END $$ LANGUAGE plpgsql;
    """)
    for table in ("credit_ledger_transactions", "credit_ledger_postings"):
        op.execute(f"""
            CREATE TRIGGER trg_{table}_immutable
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION billing_forbid_mutation();
        """)
    for table in ("credit_grants", "credit_consumptions", "billable_events", "rated_charges"):
        op.execute(f"""
            CREATE TRIGGER trg_{table}_nodelete
            BEFORE DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION billing_forbid_mutation();
        """)

    # 3. Published versions: financial fields frozen; only published→retired
    #    may change status, and DELETE is forbidden once published.
    op.execute("""
        CREATE OR REPLACE FUNCTION billing_check_version_immutable() RETURNS trigger AS $$
        BEGIN
            IF TG_OP = 'DELETE' THEN
                IF OLD.status <> 'draft' THEN
                    RAISE EXCEPTION 'published/retired pricing versions cannot be deleted';
                END IF;
                RETURN OLD;
            END IF;
            IF OLD.status = 'draft' THEN
                RETURN NEW;
            END IF;
            IF OLD.status = 'published' AND NEW.status IN ('published', 'retired') THEN
                IF NEW.config_hash IS NOT DISTINCT FROM OLD.config_hash
                   AND NEW.version_number = OLD.version_number
                   AND NEW.published_at IS NOT DISTINCT FROM OLD.published_at THEN
                    RETURN NEW;
                END IF;
            END IF;
            RAISE EXCEPTION 'pricing version % is % and immutable', OLD.id, OLD.status;
        END $$ LANGUAGE plpgsql;
    """)
    for table in ("commercial_pricing_versions", "provider_cost_versions"):
        op.execute(f"""
            CREATE TRIGGER trg_{table}_immutable
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION billing_check_version_immutable();
        """)
    # Rates of a published provider-cost version are frozen too.
    op.execute("""
        CREATE OR REPLACE FUNCTION billing_check_rate_immutable() RETURNS trigger AS $$
        DECLARE
            v_status TEXT;
        BEGIN
            SELECT status INTO v_status FROM provider_cost_versions
            WHERE id = COALESCE(NEW.provider_cost_version_id, OLD.provider_cost_version_id);
            IF v_status <> 'draft' THEN
                RAISE EXCEPTION 'rates of a % provider-cost version are immutable', v_status;
            END IF;
            IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
            RETURN NEW;
        END $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_provider_cost_rates_immutable
        BEFORE UPDATE OR DELETE ON provider_cost_rates
        FOR EACH ROW EXECUTE FUNCTION billing_check_rate_immutable();
    """)


def downgrade() -> None:
    # Hand-verified against the models; frozen — do not regenerate.
    op.drop_index('ix_rc_account', table_name='rated_charges')
    op.drop_table('rated_charges')
    op.drop_index('ix_cc_transaction', table_name='credit_consumptions')
    op.drop_index('ix_cc_grant', table_name='credit_consumptions')
    op.drop_table('credit_consumptions')
    op.drop_index('ix_clp_transaction', table_name='credit_ledger_postings')
    op.drop_index('ix_clp_ledger_account', table_name='credit_ledger_postings')
    op.drop_table('credit_ledger_postings')
    op.drop_index('ix_credit_grants_account_status', table_name='credit_grants')
    op.drop_table('credit_grants')
    op.drop_index('ix_holds_account_status', table_name='billing_holds')
    op.drop_table('billing_holds')
    op.drop_table('agent_hosting_periods')
    op.drop_table('usage_rollups')
    op.drop_index('ix_ra_agent', table_name='resource_allocations')
    op.drop_table('resource_allocations')
    op.drop_index('ix_clt_account_seq', table_name='credit_ledger_transactions')
    op.drop_table('credit_ledger_transactions')
    op.drop_index('ix_be_call', table_name='billable_events')
    op.drop_index('ix_be_account_event_at', table_name='billable_events')
    op.drop_table('billable_events')
    op.drop_table('account_balance_projections')
    op.drop_table('billing_accounts')
    op.drop_table('agent_limit_periods')
    op.drop_table('agent_credit_limits')
    op.drop_table('provider_cost_rates')
    op.drop_table('pricing_simulations')
    op.drop_table('commercial_pricing_rollouts')
    op.drop_index('ix_cpa_account_effective', table_name='commercial_pricing_assignments')
    op.drop_table('commercial_pricing_assignments')
    op.drop_table('provider_cost_versions')
    op.drop_table('commercial_pricing_versions')
    op.drop_table('processed_webhooks')
    op.drop_index('ix_bo_claim', table_name='billing_outbox')
    op.drop_table('billing_outbox')
